# Generated by Django 5.0.6 on 2026-09-02 09:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('albums', '0001_initial'),
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='genres/')),
                ('color_hex', models.CharField(default='#00F5D4', max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('audio_file', models.FileField(upload_to='audio/masters/%Y/%m/')),
                ('cover_art', models.ImageField(blank=True, null=True, upload_to='covers/songs/%Y/%m/')),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('bitrate_kbps', models.PositiveIntegerField(default=320)),
                ('sample_rate_hz', models.PositiveIntegerField(default=44100)),
                ('is_explicit', models.BooleanField(default=False)),
                ('is_premium_only', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('play_count', models.PositiveBigIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('waveform_data', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tracks', to='albums.album')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='artists.artist')),
                ('genre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='music.genre')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
