# Generated by Django 5.0.6 on 2026-09-02 10:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_recordlabel_alter_album_options_album_copyright_line_and_more'),
        ('artists', '0002_artist_country_of_origin_artist_follower_count_and_more'),
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mood',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=60, unique=True)),
                ('icon', models.CharField(default='✨', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='SongContributor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Contributor stage or legal name', max_length=150)),
                ('role', models.CharField(choices=[('featured_artist', 'Featured Vocalist / Artist'), ('producer', 'Music Producer'), ('composer', 'Composer / Songwriter'), ('lyricist', 'Lyricist'), ('mix_engineer', 'Mix Engineer'), ('mastering_engineer', 'Mastering Engineer'), ('session_musician', 'Session Instrumentalist')], default='producer', max_length=30)),
                ('instrument', models.CharField(blank=True, help_text='e.g., Electric Guitar, Synthesizer', max_length=100)),
                ('royalty_split_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
            ],
        ),
        migrations.CreateModel(
            name='SongFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('format_type', models.CharField(choices=[('mp3_320', 'MP3 (320 kbps High Quality)'), ('flac_1411', 'FLAC (1411 kbps Studio Master Lossless)'), ('aac_96', 'AAC (96 kbps Data Saver)'), ('wav_raw', 'WAV Master Stem')], default='mp3_320', max_length=20)),
                ('file', models.FileField(upload_to='audio/encoded/%Y/%m/')),
                ('bitrate_kbps', models.PositiveIntegerField(default=320)),
                ('file_size_bytes', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment_text', models.TextField(max_length=1000)),
                ('timestamp_seconds', models.FloatField(blank=True, help_text='Optional audio timestamp where comment is pinned', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('is_flagged', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stars', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='genre',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='genre',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='bpm',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Beats per minute (tempo)', null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='channels',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='song',
            name='copyright_line',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='song',
            name='is_original_master',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='song',
            name='isrc_code',
            field=models.CharField(blank=True, help_text='International Standard Recording Code', max_length=20),
        ),
        migrations.AddField(
            model_name='song',
            name='musical_key',
            field=models.CharField(blank=True, help_text='e.g., C Major, F# Minor', max_length=10),
        ),
        migrations.AddField(
            model_name='song',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(db_index=True, max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, upload_to='audio/masters/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='song',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, help_text='Duration in seconds'),
        ),
        migrations.AlterField(
            model_name='song',
            name='is_premium_only',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='song',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='like_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='play_count',
            field=models.PositiveBigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='slug',
            field=models.SlugField(max_length=240),
        ),
        migrations.AlterField(
            model_name='song',
            name='waveform_data',
            field=models.JSONField(blank=True, default=list, help_text='Array of normalized float amplitude peaks'),
        ),
        migrations.CreateModel(
            name='Lyrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plain_lyrics', models.TextField(help_text='Unsynchronized full song lyrics')),
                ('is_synced', models.BooleanField(default=False)),
                ('synced_lyrics_json', models.JSONField(blank=True, default=list, help_text='Array of objects: [{"time": 12.5, "text": "Verse 1 line"}]')),
                ('writer_credit', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lyrics', to='music.song')),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='moods',
            field=models.ManyToManyField(blank=True, related_name='songs', to='music.mood'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['artist', 'is_published'], name='music_song_artist__ddbbea_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['genre', 'play_count'], name='music_song_genre_i_a9a547_idx'),
        ),
        migrations.AddIndex(
            model_name='song',
            index=models.Index(fields=['is_premium_only', 'is_published'], name='music_song_is_prem_7f6061_idx'),
        ),
        migrations.AddField(
            model_name='songcontributor',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credited_tracks', to='artists.artist'),
        ),
        migrations.AddField(
            model_name='songcontributor',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='music.song'),
        ),
        migrations.AddField(
            model_name='songfile',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encoded_files', to='music.song'),
        ),
        migrations.AddField(
            model_name='trackcomment',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='music.song'),
        ),
        migrations.AddField(
            model_name='trackcomment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trackrating',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='music.song'),
        ),
        migrations.AddField(
            model_name='trackrating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='track_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='songfile',
            unique_together={('song', 'format_type')},
        ),
        migrations.AlterUniqueTogether(
            name='trackrating',
            unique_together={('user', 'song')},
        ),
    ]
