# Generated by Django 5.0.6 on 2026-09-02 09:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistEarningsDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('stream_count', models.PositiveIntegerField(default=0)),
                ('estimated_revenue_usd', models.DecimalField(decimal_places=4, default=0.0, max_digits=10)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_earnings', to='artists.artist')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'artist')},
            },
        ),
        migrations.CreateModel(
            name='DailyPlayCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_plays', models.PositiveIntegerField(default=0)),
                ('unique_listeners', models.PositiveIntegerField(default=0)),
                ('complete_plays', models.PositiveIntegerField(default=0)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='music.song')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('date', 'song')},
            },
        ),
    ]
