# Generated by Django 5.0.6 on 2026-09-02 10:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('artists', '0002_artist_country_of_origin_artist_follower_count_and_more'),
        ('music', '0002_mood_songcontributor_songfile_trackcomment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPlatformMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, unique=True)),
                ('total_streams', models.PositiveBigIntegerField(default=0)),
                ('unique_listeners', models.PositiveIntegerField(default=0)),
                ('new_users_registered', models.PositiveIntegerField(default=0)),
                ('new_tracks_uploaded', models.PositiveIntegerField(default=0)),
                ('bandwidth_served_gb', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('royalty_accrued_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StreamGeoHeatmap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(db_index=True, max_length=5)),
                ('country_name', models.CharField(max_length=100)),
                ('stream_count', models.PositiveBigIntegerField(default=0)),
                ('listener_count', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-stream_count'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='dailyplaycount',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='dailyplaycount',
            name='song',
        ),
        migrations.CreateModel(
            name='SuspiciousActivityFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField()),
                ('flag_reason', models.CharField(max_length=200)),
                ('stream_burst_count', models.PositiveIntegerField(default=0)),
                ('is_blocked', models.BooleanField(default=True)),
                ('flagged_at', models.DateTimeField(auto_now_add=True)),
                ('target_artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artists.artist')),
                ('target_song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.song')),
            ],
            options={
                'ordering': ['-flagged_at'],
            },
        ),
        migrations.DeleteModel(
            name='ArtistEarningsDaily',
        ),
        migrations.DeleteModel(
            name='DailyPlayCount',
        ),
    ]
