# Generated by Django 5.0.6 on 2026-09-02 10:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_mood_songcontributor_songfile_trackcomment_and_more'),
        ('playlists', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistCollaborator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('viewer', 'Can View Only'), ('editor', 'Can Add & Remove Tracks'), ('admin', 'Can Manage Settings & Collaborators')], default='editor', max_length=20)),
                ('invited_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistTrack',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(db_index=True, default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position', 'added_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='playlistsong',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='playlistsong',
            name='playlist',
        ),
        migrations.RemoveField(
            model_name='playlistsong',
            name='song',
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='is_public',
        ),
        migrations.AddField(
            model_name='playlist',
            name='is_featured_curated',
            field=models.BooleanField(default=False, help_text='Featured on homepage by editorial team'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlist',
            name='play_count',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playlist',
            name='privacy',
            field=models.CharField(choices=[('public', 'Public (Discoverable by Everyone)'), ('unlisted', 'Unlisted (Only with Link)'), ('private', 'Private (Only Creator & Collaborators)')], db_index=True, default='public', max_length=20),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='follower_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='is_collaborative',
            field=models.BooleanField(default=False, help_text='Allow invited users to add tracks'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='slug',
            field=models.SlugField(max_length=180),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=models.CharField(db_index=True, max_length=150),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['owner', 'privacy'], name='playlists_p_owner_i_fe768a_idx'),
        ),
        migrations.AddIndex(
            model_name='playlist',
            index=models.Index(fields=['is_featured_curated', '-follower_count'], name='playlists_p_is_feat_1b47ea_idx'),
        ),
        migrations.AddField(
            model_name='playlistcollaborator',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborators', to='playlists.playlist'),
        ),
        migrations.AddField(
            model_name='playlistcollaborator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborating_playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlistfollower',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='playlists.playlist'),
        ),
        migrations.AddField(
            model_name='playlistfollower',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_playlists', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlisttrack',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playlisttrack',
            name='playlist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_tracks', to='playlists.playlist'),
        ),
        migrations.AddField(
            model_name='playlisttrack',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='playlist_entries', to='music.song'),
        ),
        migrations.DeleteModel(
            name='PlaylistSong',
        ),
        migrations.AlterUniqueTogether(
            name='playlistcollaborator',
            unique_together={('playlist', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='playlistfollower',
            unique_together={('playlist', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='playlisttrack',
            unique_together={('playlist', 'song')},
        ),
    ]
