# Generated by Django 5.0.6 on 2026-09-02 09:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('album_type', models.CharField(choices=[('lp', 'Full Studio Album (LP)'), ('ep', 'Extended Play (EP)'), ('single', 'Single Release'), ('compilation', 'Compilation / Anthology')], default='lp', max_length=20)),
                ('cover_art', models.ImageField(blank=True, null=True, upload_to='covers/albums/%Y/%m/')),
                ('release_date', models.DateField(blank=True, null=True)),
                ('record_label', models.CharField(blank=True, max_length=150)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to='artists.artist')),
            ],
        ),
    ]
