# Generated by Django 5.0.6 on 2026-09-02 10:14

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecordLabel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='labels/')),
            ],
        ),
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-release_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='album',
            name='copyright_line',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='album',
            name='is_explicit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='album',
            name='total_discs',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='album',
            name='upc_code',
            field=models.CharField(blank=True, help_text='Universal Product Code', max_length=30),
        ),
        migrations.AddField(
            model_name='album',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_type',
            field=models.CharField(choices=[('lp', 'Full Studio Album (LP)'), ('ep', 'Extended Play (EP)'), ('single', 'Single Track Release'), ('compilation', 'Compilation / Anthology'), ('live', 'Live Concert Recording'), ('remix', 'Remix Collection')], default='lp', max_length=20),
        ),
        migrations.AlterField(
            model_name='album',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='release_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='slug',
            field=models.SlugField(max_length=240),
        ),
        migrations.CreateModel(
            name='DiscEdition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_name', models.CharField(max_length=100)),
                ('bonus_features', models.TextField(blank=True)),
                ('is_hi_res_exclusive', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='albums.album')),
            ],
        ),
        migrations.AlterField(
            model_name='album',
            name='record_label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releases', to='albums.recordlabel'),
        ),
        migrations.CreateModel(
            name='AlbumReview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(max_length=3000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='albums.album')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('album', 'user')},
            },
        ),
        migrations.CreateModel(
            name='AlbumTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disc_number', models.PositiveSmallIntegerField(default=1)),
                ('track_number', models.PositiveSmallIntegerField(default=1)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_tracks', to='albums.album')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_associations', to='music.song')),
            ],
            options={
                'ordering': ['disc_number', 'track_number'],
                'unique_together': {('album', 'disc_number', 'track_number')},
            },
        ),
    ]
