# Generated by Django 5.0.6 on 2026-09-02 10:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_artist_country_of_origin_artist_follower_count_and_more'),
        ('music', '0002_mood_songcontributor_songfile_trackcomment_and_more'),
        ('player', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaybackQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaybackSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('progress_seconds', models.PositiveIntegerField(default=0)),
                ('is_playing', models.BooleanField(default=False)),
                ('is_shuffled', models.BooleanField(default=False)),
                ('repeat_mode', models.CharField(choices=[('off', 'Repeat Off'), ('all', 'Repeat All Queue'), ('one', 'Repeat Single Track')], default='off', max_length=10)),
                ('volume_percent', models.PositiveSmallIntegerField(default=80)),
                ('active_device_name', models.CharField(default='Web Browser', max_length=100)),
                ('last_ping', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QueueItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField(db_index=True, default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['position', 'added_at'],
            },
        ),
        migrations.CreateModel(
            name='RadioStation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='likedsong',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='likedsong',
            name='song',
        ),
        migrations.RemoveField(
            model_name='likedsong',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userqueue',
            name='current_song',
        ),
        migrations.RemoveField(
            model_name='userqueue',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='listeninghistory',
            options={'ordering': ['-played_at']},
        ),
        migrations.RemoveField(
            model_name='listeninghistory',
            name='completed_stream',
        ),
        migrations.RemoveField(
            model_name='listeninghistory',
            name='duration_played_seconds',
        ),
        migrations.AddField(
            model_name='listeninghistory',
            name='completion_percentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='listeninghistory',
            name='device_info',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='listeninghistory',
            name='seconds_played',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='listeninghistory',
            name='was_skipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='listeninghistory',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='listeninghistory',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_logs', to='music.song'),
        ),
        migrations.AddIndex(
            model_name='listeninghistory',
            index=models.Index(fields=['user', '-played_at'], name='player_list_user_id_89d25f_idx'),
        ),
        migrations.AddIndex(
            model_name='listeninghistory',
            index=models.Index(fields=['song', '-played_at'], name='player_list_song_id_703a6e_idx'),
        ),
        migrations.AddField(
            model_name='favoritetrack',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='music.song'),
        ),
        migrations.AddField(
            model_name='favoritetrack',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_tracks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playbackqueue',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playback_queue', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playbacksession',
            name='current_song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='music.song'),
        ),
        migrations.AddField(
            model_name='playbacksession',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='playback_session', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='queueitem',
            name='queue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='player.playbackqueue'),
        ),
        migrations.AddField(
            model_name='queueitem',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song'),
        ),
        migrations.AddField(
            model_name='radiostation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='radiostation',
            name='seed_artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='artists.artist'),
        ),
        migrations.AddField(
            model_name='radiostation',
            name='seed_genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.genre'),
        ),
        migrations.AddField(
            model_name='radiostation',
            name='seed_song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='music.song'),
        ),
        migrations.DeleteModel(
            name='LikedSong',
        ),
        migrations.DeleteModel(
            name='UserQueue',
        ),
        migrations.AlterUniqueTogether(
            name='favoritetrack',
            unique_together={('user', 'song')},
        ),
    ]
