# Generated by Django 5.0.6 on 2026-09-02 09:47

import accounts.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', 'Primary Artist Owner'), ('manager', 'Artist Manager / Label Rep'), ('producer', 'Producer / Contributor'), ('member', 'Band Member')], default='owner', max_length=30)),
                ('can_upload_music', models.BooleanField(default=True)),
                ('can_manage_releases', models.BooleanField(default=True)),
                ('can_view_analytics', models.BooleanField(default=True)),
                ('can_withdraw_funds', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SecurityQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=255)),
                ('answer_hash', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwoFactorAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_key', models.CharField(help_text='Base32 encoded TOTP secret key', max_length=64)),
                ('is_enabled', models.BooleanField(default=False)),
                ('backup_codes', models.JSONField(default=list, help_text='List of one-time backup hash codes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_quality', models.CharField(choices=[('low', 'Data Saver (96 kbps)'), ('standard', 'Standard High Quality (320 kbps MP3)'), ('lossless', 'Hi-Fi Lossless (1411 kbps FLAC) - Premium Only')], default='standard', max_length=20)),
                ('normalize_volume', models.BooleanField(default=True, help_text='ReplayGain audio normalization.')),
                ('enable_crossfade', models.BooleanField(default=False)),
                ('crossfade_seconds', models.PositiveIntegerField(default=3)),
                ('equalizer_preset', models.CharField(default='Flat', max_length=50)),
                ('gapless_playback', models.BooleanField(default=True)),
                ('visualizer_mode', models.CharField(choices=[('3d-particle-mesh', '3D Cosmic Particle Mesh (Three.js)'), ('neon-bars', 'Neon Cyber Frequency Bars'), ('tunnel-vortex', '3D Warp Tunnel Visualizer'), ('minimal-wave', 'Minimal Sine Waveform'), ('off', 'Visualizer Disabled (Battery Saver)')], default='3d-particle-mesh', max_length=30)),
                ('visualizer_sensitivity', models.FloatField(default=1.0)),
                ('visualizer_bloom_effect', models.BooleanField(default=True)),
                ('theme', models.CharField(default='dark-cosmic', max_length=30)),
                ('email_on_new_release', models.BooleanField(default=True)),
                ('email_on_playlist_like', models.BooleanField(default=True)),
                ('email_on_artist_update', models.BooleanField(default=True)),
                ('email_newsletter', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, help_text='Tell the community about yourself and your taste.', max_length=1000)),
                ('headline', models.CharField(blank=True, help_text='Short tagline displayed on profile header.', max_length=150)),
                ('website', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, default='United States', max_length=60)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('header_banner', models.ImageField(blank=True, null=True, upload_to='banners/%Y/%m/', validators=[accounts.validators.validate_image_file_extension, accounts.validators.validate_image_file_size])),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='Dictionary containing twitter, instagram, soundcloud, spotify, youtube links')),
                ('is_public', models.BooleanField(default=True, help_text='Whether profile is publicly discoverable.')),
                ('show_listening_activity', models.BooleanField(default=True)),
                ('show_public_playlists', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('device_type', models.CharField(default='Desktop Browser', max_length=50)),
                ('location_city', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-last_activity'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address')),
                ('username', models.CharField(db_index=True, help_text='Required. 3-35 characters. Letters, numbers, underscores, or hyphens.', max_length=35, unique=True, validators=[accounts.validators.validate_username_format], verbose_name='username')),
                ('phone', models.CharField(blank=True, help_text='Optional international phone number for SMS alerts and account recovery.', max_length=20, null=True, validators=[accounts.validators.validate_phone_number])),
                ('role', models.CharField(choices=[('listener', 'Standard Listener'), ('artist', 'Verified Creator / Artist'), ('moderator', 'Content Moderator'), ('admin', 'Platform Administrator')], db_index=True, default='listener', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/%Y/%m/', validators=[accounts.validators.validate_image_file_extension, accounts.validators.validate_image_file_size])),
                ('is_verified', models.BooleanField(default=False, help_text='Designates email or identity verification.')),
                ('is_premium', models.BooleanField(db_index=True, default=False, help_text='True if user holds an active premium tier.')),
                ('premium_expires_at', models.DateTimeField(blank=True, null=True)),
                ('storage_quota_bytes', models.BigIntegerField(default=524288000, help_text='Default 500 MB upload limit for artists')),
                ('storage_used_bytes', models.BigIntegerField(default=0)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('failed_login_attempts', models.PositiveIntegerField(default=0)),
                ('is_locked', models.BooleanField(default=False)),
                ('lock_expires_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-date_joined'],
            },
        ),
    ]
