# Generated by Django 5.0.6 on 2026-09-02 09:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditRetentionPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('AUTH', 'Authentication & Access'), ('USER', 'User Management'), ('ARTIST', 'Artist Actions'), ('MUSIC', 'Music & Media Catalog'), ('FINANCE', 'Subscription & Financial'), ('MODERATION', 'Moderation & Takedowns'), ('SYSTEM', 'System Configuration'), ('SECURITY', 'Security Anomaly')], max_length=20, unique=True)),
                ('retention_days', models.PositiveIntegerField(default=365)),
                ('auto_archive', models.BooleanField(default=True)),
                ('last_cleaned_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=150)),
                ('target_entity', models.CharField(max_length=150)),
                ('justification_reason', models.TextField(help_text='Mandatory reasoning provided by the admin.')),
                ('changes_applied', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privileged_admin_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Privileged Action',
                'verbose_name_plural': 'Admin Privileged Actions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('endpoint', models.CharField(db_index=True, max_length=255)),
                ('method', models.CharField(max_length=10)),
                ('status_code', models.PositiveIntegerField()),
                ('execution_time_ms', models.FloatField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Request Log',
                'verbose_name_plural': 'API Request Logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SecurityEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(db_index=True, help_text='e.g., failed_login, token_expired, rate_limit_exceeded, sql_injection_pattern', max_length=100)),
                ('severity', models.CharField(choices=[('INFO', 'Informational'), ('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Severity'), ('CRITICAL', 'Critical Alert')], db_index=True, default='HIGH', max_length=20)),
                ('source_ip', models.GenericIPAddressField(db_index=True)),
                ('user_agent', models.TextField(blank=True, default='')),
                ('country_code', models.CharField(blank=True, default='XX', max_length=10)),
                ('city', models.CharField(blank=True, default='Unknown', max_length=100)),
                ('details', models.JSONField(default=dict)),
                ('is_resolved', models.BooleanField(db_index=True, default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_security_events', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='security_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Security Event',
                'verbose_name_plural': 'Security Events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_email', models.EmailField(blank=True, help_text='Snapshot of email at time of action.', max_length=254, null=True)),
                ('actor_role', models.CharField(blank=True, default='anonymous', max_length=50)),
                ('category', models.CharField(choices=[('AUTH', 'Authentication & Access'), ('USER', 'User Management'), ('ARTIST', 'Artist Actions'), ('MUSIC', 'Music & Media Catalog'), ('FINANCE', 'Subscription & Financial'), ('MODERATION', 'Moderation & Takedowns'), ('SYSTEM', 'System Configuration'), ('SECURITY', 'Security Anomaly')], db_index=True, default='AUTH', max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Informational'), ('LOW', 'Low Risk'), ('MEDIUM', 'Medium Risk'), ('HIGH', 'High Severity'), ('CRITICAL', 'Critical Alert')], db_index=True, default='INFO', max_length=20)),
                ('action_type', models.CharField(db_index=True, help_text='e.g., user.login, song.upload, subscription.canceled, admin.ban', max_length=120)),
                ('description', models.TextField(help_text='Human-readable description of what transpired.')),
                ('target_model', models.CharField(blank=True, help_text='e.g., Song, User, Invoice', max_length=100, null=True)),
                ('target_object_id', models.CharField(blank=True, max_length=255, null=True)),
                ('target_repr', models.CharField(blank=True, help_text='String representation of target', max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('request_method', models.CharField(blank=True, default='GET', max_length=10)),
                ('request_path', models.CharField(blank=True, default='', max_length=500)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('pre_change_state', models.JSONField(blank=True, help_text='JSON diff before modification', null=True)),
                ('post_change_state', models.JSONField(blank=True, help_text='JSON diff after modification', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Arbitrary extra context and parameters')),
                ('signature', models.CharField(blank=True, help_text='Cryptographic digest of the entry', max_length=128, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(blank=True, help_text='User who initiated the action, or null for system events.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['category', 'severity'], name='audit_audit_categor_a45df2_idx'), models.Index(fields=['action_type', 'timestamp'], name='audit_audit_action__74f5dd_idx'), models.Index(fields=['user', 'timestamp'], name='audit_audit_user_id_e8be02_idx'), models.Index(fields=['ip_address', 'timestamp'], name='audit_audit_ip_addr_4a1174_idx')],
            },
        ),
    ]
