# Generated by Django 5.0.6 on 2026-09-02 10:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_recordlabel_alter_album_options_album_copyright_line_and_more'),
        ('artists', '0002_artist_country_of_origin_artist_follower_count_and_more'),
        ('moderation', '0001_initial'),
        ('music', '0002_mood_songcontributor_songfile_trackcomment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentFilterRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword_pattern', models.CharField(max_length=100, unique=True)),
                ('is_regex', models.BooleanField(default=False)),
                ('severity_level', models.CharField(default='HIGH', max_length=20)),
                ('auto_quarantine', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ModerationReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.CharField(choices=[('copyright_dmca', 'Copyright Infringement (DMCA)'), ('explicit_unmarked', 'Unmarked Explicit / Mature Content'), ('hate_speech', 'Hate Speech / Harassment'), ('audio_leak', 'Unreleased / Leaked Audio'), ('spam', 'Spam / Fake Content'), ('other', 'Other Violation')], db_index=True, default='copyright_dmca', max_length=30)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('investigating', 'Under Investigation'), ('removed', 'Content Taken Down'), ('dismissed', 'Report Dismissed (No Violation)')], db_index=True, default='pending', max_length=20)),
                ('description', models.TextField(max_length=1500)),
                ('evidence_url', models.URLField(blank=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('album', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_reports', to='albums.album')),
                ('artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_reports', to='artists.artist')),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_reports', to='music.trackcomment')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='filed_reports', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_moderation_reports', to=settings.AUTH_USER_MODEL)),
                ('song', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderation_reports', to='music.song')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TakedownRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('claimant_name', models.CharField(max_length=150)),
                ('claimant_email', models.EmailField(max_length=254)),
                ('copyright_owner', models.CharField(max_length=150)),
                ('work_title', models.CharField(help_text='Original copyrighted work title', max_length=200)),
                ('statement_of_authority', models.BooleanField(default=True, help_text='Statement made under penalty of perjury')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('investigating', 'Under Investigation'), ('removed', 'Content Taken Down'), ('dismissed', 'Report Dismissed (No Violation)')], default='pending', max_length=20)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('infringing_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dmca_requests', to='music.song')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.DeleteModel(
            name='ContentReport',
        ),
    ]
