# Generated by Django 5.0.6 on 2026-09-02 10:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoCoupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('discount_percent', models.PositiveSmallIntegerField(default=20)),
                ('max_uses', models.PositiveIntegerField(default=500)),
                ('times_used', models.PositiveIntegerField(default=0)),
                ('expires_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionTier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('price_monthly_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('price_annual_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('allows_lossless', models.BooleanField(default=False, help_text='Unlocks 1411kbps FLAC streaming')),
                ('allows_offline', models.BooleanField(default=False)),
                ('allows_artist_studio', models.BooleanField(default=False)),
                ('allows_stems_download', models.BooleanField(default=False)),
                ('max_devices', models.PositiveSmallIntegerField(default=1)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='plan',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='renews_at',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='starts_at',
        ),
        migrations.RemoveField(
            model_name='usersubscription',
            name='stripe_subscription_id',
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='billing_cycle',
            field=models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual (Save 20%)')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='cancel_at_period_end',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='current_period_end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='current_period_start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='payment_customer_id',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='payment_subscription_id',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('trialing', 'In Free Trial'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('expired', 'Expired')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='active_subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SubscriptionBenefit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit_text', models.CharField(max_length=200)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='benefits', to='subscriptions.subscriptiontier')),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.AddField(
            model_name='usersubscription',
            name='tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscribers', to='subscriptions.subscriptiontier'),
        ),
        migrations.DeleteModel(
            name='SubscriptionPlan',
        ),
    ]
