# Generated by Django 5.0.6 on 2026-09-02 09:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('stage_name', models.CharField(blank=True, max_length=150)),
                ('bio', models.TextField(blank=True)),
                ('genres', models.CharField(blank=True, help_text='Comma-separated genres', max_length=255)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='artists/avatars/%Y/%m/')),
                ('header_banner', models.ImageField(blank=True, null=True, upload_to='artists/banners/%Y/%m/')),
                ('monthly_listeners', models.PositiveIntegerField(db_index=True, default=0)),
                ('total_streams', models.PositiveBigIntegerField(default=0)),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Verification Pending'), ('verified', 'Verified Artist'), ('rejected', 'Verification Rejected')], db_index=True, default='unverified', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('unpaid_balance', models.DecimalField(decimal_places=4, default=0.0, max_digits=12)),
                ('total_paid_out', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('website', models.URLField(blank=True)),
                ('spotify_id', models.CharField(blank=True, max_length=100)),
                ('soundcloud_id', models.CharField(blank=True, max_length=100)),
                ('youtube_channel', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(help_text='Primary account associated with this artist entity.', on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-monthly_listeners', 'name'],
            },
        ),
    ]
