# Generated by Django 5.0.6 on 2026-09-02 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0001_initial'),
        ('music', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='country_of_origin',
            field=models.CharField(blank=True, default='Global', max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='follower_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='artist',
            name='instagram_handle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='artist',
            name='pinned_song',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='music.song'),
        ),
        migrations.AddField(
            model_name='artist',
            name='royalty_split_rate',
            field=models.DecimalField(decimal_places=4, default=0.0045, help_text='USD per stream', max_digits=5),
        ),
        migrations.AddField(
            model_name='artist',
            name='twitter_handle',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='artist',
            name='slug',
            field=models.SlugField(max_length=180, unique=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='total_streams',
            field=models.PositiveBigIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(help_text='Primary user account that owns and manages this artist page.', on_delete=django.db.models.deletion.CASCADE, related_name='artist_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='artist',
            name='verification_status',
            field=models.CharField(choices=[('unverified', 'Unverified Creator'), ('pending', 'Verification Under Review'), ('verified', 'Verified Artist ✓'), ('rejected', 'Verification Declined')], db_index=True, default='unverified', max_length=20),
        ),
        migrations.CreateModel(
            name='ArtistMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('role_instrument', models.CharField(help_text='e.g. Lead Vocals, Bass, Keyboards', max_length=120)),
                ('joined_year', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='artists.artist')),
            ],
        ),
        migrations.CreateModel(
            name='ArtistVerificationRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('legal_name', models.CharField(max_length=150)),
                ('official_id_document', models.FileField(blank=True, null=True, upload_to='verification_docs/%Y/%m/')),
                ('social_proof_links', models.TextField(help_text='Links to official Instagram, Spotify for Artists, Twitter, or Website')),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('unverified', 'Unverified Creator'), ('pending', 'Verification Under Review'), ('verified', 'Verified Artist ✓'), ('rejected', 'Verification Declined')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_requests', to='artists.artist')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='PayoutAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('stripe_connect', 'Stripe Direct Bank Transfer'), ('paypal', 'PayPal MassPay Account'), ('wire_iban', 'International Wire Transfer (IBAN/SWIFT)')], default='stripe_connect', max_length=30)),
                ('account_identifier', models.CharField(help_text='Stripe Account ID, PayPal Email, or IBAN', max_length=150)),
                ('beneficiary_name', models.CharField(max_length=150)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('is_verified', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payout_account', to='artists.artist')),
            ],
        ),
        migrations.CreateModel(
            name='RoyaltyStatement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('total_streams', models.PositiveIntegerField(default=0)),
                ('gross_earnings_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('platform_fee_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('net_payable_usd', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_paid', models.BooleanField(default=False)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='royalty_statements', to='artists.artist')),
            ],
            options={
                'ordering': ['-period_start'],
            },
        ),
        migrations.CreateModel(
            name='ArtistFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='artists.artist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_artists', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('user', 'artist')},
            },
        ),
    ]
