# Generated by Django 5.0.6 on 2026-09-02 09:47

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrendingSnapshot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('snapshot_date', models.DateField(auto_now_add=True, db_index=True)),
                ('top_song_ids', models.JSONField(default=list)),
                ('top_artist_ids', models.JSONField(default=list)),
                ('top_album_ids', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-snapshot_date'],
            },
        ),
    ]
