# Generated by Django 5.0.6 on 2026-09-02 10:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discovery', '0001_initial'),
        ('music', '0002_mood_songcontributor_songfile_trackcomment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveSmallIntegerField(db_index=True)),
                ('previous_rank', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('peak_rank', models.PositiveSmallIntegerField(default=1)),
                ('weeks_on_chart', models.PositiveSmallIntegerField(default=1)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song')),
            ],
            options={
                'ordering': ['rank'],
            },
        ),
        migrations.CreateModel(
            name='FeaturedBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=250)),
                ('badge_text', models.CharField(default='FEATURED RELEASE', max_length=50)),
                ('banner_image', models.ImageField(upload_to='banners/%Y/%m/')),
                ('action_url', models.CharField(max_length=255)),
                ('action_button_text', models.CharField(default='Listen Now', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MusicChart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('chart_type', models.CharField(choices=[('top_50_global', 'Global Top 50'), ('viral_trending', 'Viral Trending 50'), ('genre_spotlight', 'Genre Spotlight'), ('new_discovery', 'Fresh Discoveries')], default='top_50_global', max_length=30)),
                ('description', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='charts/%Y/%m/')),
                ('is_published', models.BooleanField(db_index=True, default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SearchQueryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query_text', models.CharField(db_index=True, max_length=200)),
                ('results_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrendingMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('velocity_score', models.FloatField(db_index=True, default=0.0)),
                ('streams_last_24h', models.PositiveIntegerField(default=0)),
                ('streams_last_7d', models.PositiveIntegerField(default=0)),
                ('calculated_at', models.DateTimeField(auto_now=True)),
                ('song', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trending_metric', to='music.song')),
            ],
        ),
        migrations.DeleteModel(
            name='TrendingSnapshot',
        ),
        migrations.AddField(
            model_name='chartentry',
            name='chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='discovery.musicchart'),
        ),
        migrations.AlterUniqueTogether(
            name='chartentry',
            unique_together={('chart', 'song')},
        ),
    ]
