# Generated by Django 5.0.6 on 2026-09-02 10:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notify_new_releases', models.BooleanField(default=True)),
                ('notify_playlist_collaborations', models.BooleanField(default=True)),
                ('notify_social_followers', models.BooleanField(default=True)),
                ('notify_royalty_earnings', models.BooleanField(default=True)),
                ('notify_security_events', models.BooleanField(default=True)),
                ('email_digests', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='notification',
            name='target_url',
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, help_text='Link to direct the user to', max_length=255),
        ),
        migrations.AddField(
            model_name='notification',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='message',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('new_release', 'New Release from Followed Artist'), ('playlist_add', 'Song Added to Collaborative Playlist'), ('new_follower', 'New Follower on Profile/Artist'), ('royalty_payout', 'Royalty Payout Processed'), ('verification_update', 'Artist Verification Decision'), ('security_alert', 'Account Security Alert'), ('system_announcement', 'MusicVerse Platform Announcement')], default='system_announcement', max_length=30),
        ),
        migrations.AlterField(
            model_name='notification',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='notificatio_recipie_684eac_idx'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL),
        ),
    ]
