# Generated by Django 5.0.6 on 2026-09-02 10:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_mood_songcontributor_songfile_trackcomment_and_more'),
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMix',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mix_number', models.PositiveSmallIntegerField(default=1)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(blank=True, max_length=250)),
                ('cover_image_url', models.URLField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_mixes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['mix_number'],
                'unique_together': {('user', 'mix_number')},
            },
        ),
        migrations.CreateModel(
            name='DailyMixTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('mix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='recommendations.dailymix')),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('mix', 'song')},
            },
        ),
        migrations.CreateModel(
            name='RecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_source', models.CharField(default='collaborative_filter', max_length=50)),
                ('was_clicked', models.BooleanField(default=False)),
                ('was_completed', models.BooleanField(default=False)),
                ('recommended_at', models.DateTimeField(auto_now_add=True)),
                ('song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.song')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-recommended_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('similarity_score', models.FloatField(db_index=True, default=0.0)),
                ('source_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_from', to='music.song')),
                ('target_song', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='similarities_to', to='music.song')),
            ],
        ),
        migrations.CreateModel(
            name='UserTasteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_genres', models.JSONField(blank=True, default=list, help_text='Array of top genre slugs with affinity scores')),
                ('top_artists', models.JSONField(blank=True, default=list)),
                ('preferred_min_bpm', models.PositiveSmallIntegerField(default=80)),
                ('preferred_max_bpm', models.PositiveSmallIntegerField(default=160)),
                ('diversity_score', models.FloatField(default=0.5, help_text='Tendency to explore new versus familiar tracks (0.0 to 1.0)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='taste_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='RecommendationSnapshot',
        ),
        migrations.AddIndex(
            model_name='tracksimilarity',
            index=models.Index(fields=['source_song', '-similarity_score'], name='recommendat_source__089a55_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tracksimilarity',
            unique_together={('source_song', 'target_song')},
        ),
    ]
